version: '3.1'
services:
  stats-server:
    build: static-service
    image: stats
    container_name: explore-with-me-stats
    depends_on:
      - ewm-service
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: explore-with-me-stats-postgres
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=static_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: event-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
